; PlatformIO Project Configuration File for NEXORA
; Smart Personal Information Station
; Target MCU: Arduino Nano ESP32 (ESP32-S3)
; Display: 3.5" ILI9488 TFT LCD (8-Bit Parallel Mode)

[platformio]
default_envs = nano_esp32

[env:nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

upload_protocol = esptool
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

build_flags =
    -D BOARD_USES_HW_GPIO_NUMBERS
    -D CORE_DEBUG_LEVEL=3
    -D MQTT_MAX_PACKET_SIZE=2048
    -O2

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8
